### ISSUE TITLE
Update to manage alerts that trigger stop

### ISSUE THREAD

**Issue by jewzaam** [jewzaam/minecraft-ansible#2]
To ensure I don't run up a bill for not using something I want to have the server shutdown when network in is less than 1000 bytes (aka nobody is using the server) for 5 minutes.

Easy to do manually, want to automate it.

**Comment by jewzaam** [comment]
Hitting issue with how to define the actions for the alarm.

https://stackoverflow.com/questions/31295711/alarm-action-definition-in-ec2-metric-alarm-ansible-module

```
  - name: Setup CloudWatch alarm to stop instance
    ec2_metric_alarm:
      state: present
      region: "{{ minecraft.ec2.region }}"
      alarm_actions: ?????
      evaluation_periods: 1
      metric: NetworkIn
      name: alarm_minecraft_low_network_stop
      period: 300
      unit: Bytes
      threshold: 1000
      comparison: "<"
      dimensions: {'InstanceId': "{{ item.id }}"}
      statistic: Average
    with_items: "{{ instance_out.instances }}"
    when: minecraft.server.stop_when is defined
```

Not sure what to have set in alarm_actions yet.
